apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebsite
  labels:
     env: staging
     type: website
     owner: Matvey_Guralskiy
spec:
  replicas: 3
  selector:
    matchLabels:
       based: apache   #Label tag for Pods
  template:
    metadata:
      labels:
       based: apache
    spec:
      containers:
          - name: simple-website
            image: matveyguralskiy/simple_website:V2.0
            ports:
               - containerPort: 80


---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mywebsite
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myapp-autoscaling
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
       name: cpu
       target:
         type: Utilization
         averageUtilization: 70
  - type: Resource
    resource:
       name: memory
       target:
         type: Utilization
         averageUtilization: 80