apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-control
  labels:
     app: simple_website
spec:
  replicas: 2
  selector:
    matchLabels:
       based: simple_website   # Label tag for Pods
  template:
    metadata:
      labels:
       based: simple_website
    spec:
      containers:
        - name: myapp-1
          image: matveyguralskiy/simple_website:V2.0
          ports:
            - containerPort: 80     # Port on Pod
        - name: myapp-2
          image: tomcat:latest
          ports:
            - containerPort: 8080   # Port on Pod
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: myapp-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myapp-control 
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
       name: cpu
       target:
         type: Utilization
         averageUtilization: 70
  - type: Resource
    resource:
       name: memory
       target:
         type: Utilization
         averageUtilization: 80
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
  labels:
    env: staging
    type: website
    owner: Matvey_Guralskiy
spec:
  type: LoadBalancer
  selector:
    based: simple_website
  ports:
    - name: app-listener-1
      protocol: TCP
      port: 80                     # Port on Load-Balancer
      targetPort: 80               # Port on Pod

    - name: app-listener-2
      protocol: TCP
      port: 8000                   # Port on Load-Balancer
      targetPort: 8080             # Port on Pod